### ISSUE TITLE
python test/script can not pass

### ISSUE THREAD

**Issue by AileenLin** [duckdb/extension-template#32]
## Steps to reproduce:
1. Create a new repo from latest template
2. run make
3. `pip install duckdb --pre --upgrade`
4. run `python3 -m pytest` under dir `test/python`

## Expected result:
python test passed

## Actual result:
>       conn.execute(f"load '{extension_binary}'")
> E       duckdb.duckdb.InvalidInputException: Invalid Input Error: Initialization function "quack_init" from file "/path/to/duckdb-template/build/release/extension/quack/quack.duckdb_extension" threw an exception: "INTERNAL Error: Missing DB manager"

**Comment by hannes** [comment]
The extension template is in flux right now, maybe @samansmink can have a look?

**Comment by samansmink** [comment]
I'm suspecting a mismatch between duckdb and extension is the culprit here, but i have not managed to reproduce. 

Anyway this is not the recommended way to run the python tests: The recommended way is using the `debug_python` or `release_python` targets in the Makefile. These build duckdb from source using duckdb from the submodule. Note that you may have to remove the currently installed duckdb package with pip for this to work properly.

Let me know if this works for you! Either way with the upcoming 0.9.0 release of duckdb we will aim to have a stable version of the extension template that will make things simpler as you can then just build for the latests stable version of duckdb
